version: "3"
services:
  web:
    build:
      context: .
    image: jhkersul/kersul-pantry-api
    hostname: kersul-pantry-api
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=development
      - COSMOS_ACCESS_TOKEN=fake-access-token
