version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13

    working_directory: ~/kersul-pantry-api

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: 'Install dependencies'
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: 'Lint code'
          command: yarn lint

      - run:
          name: 'Tests'
          command: yarn test
